project:
  type: website
  output-dir: docs

website:
  title: "Math 299"
  back-to-top-navigation: true
  navbar:
    right:
      - icon: github
        href: https://github.com/rmk118/ruby-math299
    left:
      - href: index.qmd
        text: Home
      - text: HW
        menu: 
        - text: HW1
          href: ./HW/hw_01_intro_to_markdown.qmd
        - text: HW2
          href: ./HW/hw_02_fitting_lm.qmd
        - text: HW3
          href: ./HW/hw_03_diagnostics.qmd
      - text: Notes
        menu: 
          - text: Lab 1
            href: ./Notes/lab1.qmd
          - text: Inference & Diagnostics
            href: ./Notes/Inference_Diagnostics.qmd
          - text: Design Matrices
            href: ./Notes/design_matrices.qmd
    
format:
  html:
    theme: flatly
    link-external-newwindow: true
    link-external-icon: false
    toc: true
    toc-depth: 3
    df-print: kable
    code-overflow: wrap



